export type ClosetCategory =
  | "上装"
  | "下装"
  | "连衣裙"
  | "外套"
  | "鞋履"
  | "配饰";

export type ShopCategory = ClosetCategory | "美妆" | "装饰";

export type WardrobeItem = {
  id: string;
  clientId?: string;
  name: string;
  category: ClosetCategory;
  color: string;
  colorName: string;
  size: string;
  source: "我的衣服" | "虚拟商品" | "示例衣物";
  sourceUrl?: string;
  imageUrl?: string;
  season: string;
  style: string;
  chest?: number;
  waist?: number;
  hips?: number;
  length?: number;
  confidence: "高" | "中" | "待确认";
};

export type Product = {
  id: string;
  name: string;
  brand: string;
  category: ShopCategory;
  color: string;
  colorName: string;
  points: number;
  subtitle: string;
  style: string;
  shopStyles: string[];
  season: string;
  visual: string;
  spriteIndex: number;
  featuredRank: number;
  newnessRank: number;
};

export const PRODUCTS: Product[] = [
  {
    id: "p-soft-shirt",
    name: "晨雾真丝感衬衫",
    brand: "MELLOW FORM",
    category: "上装",
    color: "#e8e0d0",
    colorName: "珍珠米",
    points: 168,
    subtitle: "轻盈垂感 · 微落肩",
    style: "轻松",
    shopStyles: ["静奢感", "通勤"],
    season: "春秋",
    visual: "shirt",
    spriteIndex: 0,
    featuredRank: 1,
    newnessRank: 9,
  },
  {
    id: "p-knit",
    name: "蔷薇柔光短开衫",
    brand: "AUBE KNIT",
    category: "上装",
    color: "#e9b8aa",
    colorName: "干燥蔷薇",
    points: 139,
    subtitle: "亲肤针织 · 常规版",
    style: "温柔",
    shopStyles: ["浪漫", "约会"],
    season: "春秋",
    visual: "cardigan",
    spriteIndex: 1,
    featuredRank: 6,
    newnessRank: 15,
  },
  {
    id: "p-trousers",
    name: "苔影高腰阔腿裤",
    brand: "LENTO STUDIO",
    category: "下装",
    color: "#7d836f",
    colorName: "鼠尾草绿",
    points: 189,
    subtitle: "高腰垂感 · 宽松版",
    style: "利落",
    shopStyles: ["静奢感", "通勤"],
    season: "四季",
    visual: "pants",
    spriteIndex: 2,
    featuredRank: 2,
    newnessRank: 7,
  },
  {
    id: "p-dress",
    name: "暮光缎面吊带裙",
    brand: "MIYU EVENING",
    category: "连衣裙",
    color: "#a89ac4",
    colorName: "丁香紫",
    points: 239,
    subtitle: "柔光缎面 · 中长款",
    style: "温柔",
    shopStyles: ["浪漫", "约会"],
    season: "春夏",
    visual: "dress",
    spriteIndex: 3,
    featuredRank: 3,
    newnessRank: 16,
  },
  {
    id: "p-coat",
    name: "燕麦拿铁长风衣",
    brand: "PALE ROOM",
    category: "外套",
    color: "#b6a38d",
    colorName: "燕麦杏",
    points: 299,
    subtitle: "轻廓形 · 及膝长度",
    style: "利落",
    shopStyles: ["静奢感", "通勤"],
    season: "春秋",
    visual: "coat",
    spriteIndex: 4,
    featuredRank: 5,
    newnessRank: 11,
  },
  {
    id: "p-shoes",
    name: "云边奶油休闲鞋",
    brand: "WEEKDAY CLOUD",
    category: "鞋履",
    color: "#d9d5cb",
    colorName: "奶油白",
    points: 159,
    subtitle: "柔软鞋垫 · 适合走动",
    style: "轻松",
    shopStyles: ["极简", "假日"],
    season: "四季",
    visual: "shoes",
    spriteIndex: 5,
    featuredRank: 8,
    newnessRank: 5,
  },
  {
    id: "p-ballet-flats",
    name: "花瓣方头芭蕾鞋",
    brand: "PETAL STEP",
    category: "鞋履",
    color: "#ddb6b1",
    colorName: "贝壳粉",
    points: 149,
    subtitle: "柔软羊皮感 · 低跟",
    style: "温柔",
    shopStyles: ["浪漫", "通勤"],
    season: "春夏",
    visual: "shoes",
    spriteIndex: 6,
    featuredRank: 11,
    newnessRank: 14,
  },
  {
    id: "p-bag",
    name: "周末苔绿托特包",
    brand: "MOSS & THREAD",
    category: "配饰",
    color: "#7c8b71",
    colorName: "苔藓绿",
    points: 119,
    subtitle: "轻量帆布 · 大容量",
    style: "轻松",
    shopStyles: ["极简", "假日"],
    season: "四季",
    visual: "bag",
    spriteIndex: 7,
    featuredRank: 4,
    newnessRank: 6,
  },
  {
    id: "p-shoulder-bag",
    name: "晚餐酒红腋下包",
    brand: "CINDER ATELIER",
    category: "配饰",
    color: "#743e43",
    colorName: "勃艮第红",
    points: 209,
    subtitle: "细腻皮革感 · 弧形包身",
    style: "有点亮眼",
    shopStyles: ["约会", "静奢感"],
    season: "四季",
    visual: "bag",
    spriteIndex: 8,
    featuredRank: 7,
    newnessRank: 12,
  },
  {
    id: "p-lip",
    name: "陶土玫瑰雾面唇膏",
    brand: "NARA COLOR",
    category: "美妆",
    color: "#a9574e",
    colorName: "陶土玫瑰",
    points: 89,
    subtitle: "柔雾妆效 · 低饱和显色",
    style: "有点亮眼",
    shopStyles: ["浪漫", "约会"],
    season: "四季",
    visual: "lip",
    spriteIndex: 9,
    featuredRank: 10,
    newnessRank: 10,
  },
  {
    id: "p-perfume",
    name: "雨后玫瑰淡香精",
    brand: "HUSH SCENT",
    category: "美妆",
    color: "#d9aaa7",
    colorName: "雾粉",
    points: 179,
    subtitle: "玫瑰木质调 · 轻盈留香",
    style: "温柔",
    shopStyles: ["浪漫", "静奢感"],
    season: "四季",
    visual: "lip",
    spriteIndex: 10,
    featuredRank: 13,
    newnessRank: 13,
  },
  {
    id: "p-hoops",
    name: "晨光细圈耳环",
    brand: "LUNE STUDIO",
    category: "配饰",
    color: "#c49b5d",
    colorName: "柔金",
    points: 99,
    subtitle: "轻量金属感 · 日常尺寸",
    style: "利落",
    shopStyles: ["极简", "通勤"],
    season: "四季",
    visual: "bag",
    spriteIndex: 11,
    featuredRank: 12,
    newnessRank: 4,
  },
  {
    id: "p-pearls",
    name: "微光珍珠短项链",
    brand: "PEARL LINE",
    category: "配饰",
    color: "#e9e1d2",
    colorName: "月光白",
    points: 129,
    subtitle: "细小珍珠感 · 可调节",
    style: "温柔",
    shopStyles: ["浪漫", "静奢感"],
    season: "四季",
    visual: "bag",
    spriteIndex: 12,
    featuredRank: 9,
    newnessRank: 8,
  },
  {
    id: "p-lamp",
    name: "睡前月亮氛围灯",
    brand: "HOME MOON",
    category: "装饰",
    color: "#d8b883",
    colorName: "暖月光",
    points: 129,
    subtitle: "柔和暖光 · 三档亮度",
    style: "治愈",
    shopStyles: ["极简", "假日"],
    season: "四季",
    visual: "lamp",
    spriteIndex: 13,
    featuredRank: 14,
    newnessRank: 3,
  },
  {
    id: "p-cushion",
    name: "柔雾薰衣草靠垫",
    brand: "SOFT CORNER",
    category: "装饰",
    color: "#b7a8cc",
    colorName: "薰衣草紫",
    points: 109,
    subtitle: "短绒触感 · 可拆洗",
    style: "治愈",
    shopStyles: ["浪漫", "假日"],
    season: "四季",
    visual: "lamp",
    spriteIndex: 14,
    featuredRank: 15,
    newnessRank: 2,
  },
  {
    id: "p-vase",
    name: "鼠尾草陶瓷花器",
    brand: "STILL FORM",
    category: "装饰",
    color: "#91a18c",
    colorName: "鼠尾草绿",
    points: 119,
    subtitle: "哑光陶瓷感 · 手作轮廓",
    style: "治愈",
    shopStyles: ["极简", "静奢感"],
    season: "四季",
    visual: "lamp",
    spriteIndex: 15,
    featuredRank: 16,
    newnessRank: 1,
  },
];

export const SAMPLE_WARDROBE: WardrobeItem[] = [
  {
    id: "w-cream-tee",
    name: "奶油白基础 T 恤",
    category: "上装",
    color: "#e8e1d3",
    colorName: "奶油白",
    size: "M",
    source: "示例衣物",
    season: "四季",
    style: "轻松",
    chest: 100,
    length: 62,
    confidence: "高",
  },
  {
    id: "w-blue-shirt",
    name: "浅蓝落肩衬衫",
    category: "上装",
    color: "#aebfd1",
    colorName: "晨雾蓝",
    size: "M",
    source: "示例衣物",
    season: "春秋",
    style: "利落",
    chest: 108,
    length: 68,
    confidence: "中",
  },
  {
    id: "w-green-pants",
    name: "苔绿直筒长裤",
    category: "下装",
    color: "#626b58",
    colorName: "苔藓绿",
    size: "M",
    source: "示例衣物",
    season: "四季",
    style: "利落",
    waist: 76,
    hips: 102,
    length: 101,
    confidence: "高",
  },
  {
    id: "w-lilac-skirt",
    name: "浅紫伞摆半裙",
    category: "下装",
    color: "#9d8fb5",
    colorName: "浅丁香",
    size: "L",
    source: "示例衣物",
    season: "春夏",
    style: "温柔",
    waist: 78,
    hips: 112,
    length: 76,
    confidence: "中",
  },
  {
    id: "w-coral-dress",
    name: "珊瑚色系带连衣裙",
    category: "连衣裙",
    color: "#c77868",
    colorName: "柔珊瑚",
    size: "L",
    source: "示例衣物",
    season: "春夏",
    style: "有点亮眼",
    chest: 98,
    waist: 84,
    hips: 110,
    length: 114,
    confidence: "待确认",
  },
  {
    id: "w-oat-coat",
    name: "燕麦色轻薄风衣",
    category: "外套",
    color: "#b9a68f",
    colorName: "燕麦杏",
    size: "M",
    source: "示例衣物",
    season: "春秋",
    style: "利落",
    chest: 112,
    length: 83,
    confidence: "高",
  },
];

export const BODY_PRESETS = {
  straight: { shoulder: 40, chest: 88, waist: 76, hips: 91 },
  pear: { shoulder: 38, chest: 86, waist: 72, hips: 101 },
  hourglass: { shoulder: 40, chest: 94, waist: 70, hips: 98 },
  inverted: { shoulder: 45, chest: 96, waist: 76, hips: 89 },
  apple: { shoulder: 41, chest: 98, waist: 91, hips: 96 },
} as const;
